/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --env=production --include-runtime=false worker/worker-configuration.d.ts` (hash: 09c88147cb96f596ad146ad8f20dd403)
interface __BaseEnv_Env {
	ENVIRONMENT: "production";
	ALLOWED_ORIGINS: "https://potbelly.redcliffebay.com";
	OPENAI_REALTIME_MODEL: "gpt-realtime-2.1-mini";
	OPENAI_REALTIME_VOICE: "marin";
	OPENAI_API_KEY: string;
	AI_RATE_LIMIT_HASH_SECRET: string;
	AI_ENABLED: string;
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RateLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "OPENAI_REALTIME_MODEL" | "OPENAI_REALTIME_VOICE" | "OPENAI_API_KEY" | "AI_RATE_LIMIT_HASH_SECRET" | "AI_ENABLED">> {}
}
